mongo:
  host: "localhost"
  port: 27017
  auth:
    enabled: false
    database: "admin"
    username: ""
    password: ""

settings:
  announce-auto-save: true
  mongo: false
  use-placeholder-api: true
  health-increase: 4.00 #2 health = 1 heart
  kill-reward: 100
  death-loss: 100

scoreboard:
  title: "&b&lSoupPvP &7(Map 1)"
  normal:
    - "&7&m----------------------------"
    - "&bPlayer Name&f:&7 {player}"
    - " "
    - "&bKills&f: &7{kills}"
    - "&bDeaths&f: &7{deaths}"
    - "&bCoins&f: &7{coins}"
    - "&bSoups Used&f: &7{used}"
    - " "
    - "&7&odamt.xyz"
    - "&7&m----------------------------"
  in-combat:
    - "&7&m----------------------------"
    - "&bPlayer Name&f:&7 {player}"
    - " "
    - "&bCombat&f: &7{time}s"
    - "&bKills&f: &7{kills}"
    - "&bCoins&f: &7{coins}"
    - "&bSoups Used&f: &7{used}"
    - " "
    - "&7&odamt.xyz"
    - "&7&m----------------------------"