name: Soup
author: damt
version: 1.0
main: xyz.damt.Soup
description: SoupPvP Plugin Created By Damt.
commands:
  pay:
    aliases: [p2p, send]
    description: Sends money to a specific user
  balance:
    aliases: [bal, coins]
    description: Showcases the amount of a coins the player has
  stats:
    aliases: [statistics]
    description: Shows a player a gui showcasing their statistics
  debug:
    aliases: [admindebug]
    description: Debug command for admins
  kits:
    description: Opens the kit menu
  kit:
    description: Main kit commmand
  build:
    aliases: [buildmode]
    description: To allow building for you only
  setspawn:
    aliases: [spawnset]
    description: Sets the spawn for your world